[package]
name = "bevy_ecs_tilemap"
description = "A tilemap rendering plugin for bevy which is more ECS friendly by having an entity per tile."
version = "0.4.0"
authors = ["John Mitchell"]
homepage = "https://github.com/StarArawn/bevy_ecs_tilemap"
repository = "https://github.com/StarArawn/bevy_ecs_tilemap"
license-file = "LICENSE"
edition = "2018"
exclude = ["assets/*", "screenshots/*"]

[features]
default = []
ldtk = ["anyhow", "ldtk_rust", "serde_json"]
tiled_map = ["anyhow", "tiled"]

[dependencies]
anyhow = { version = "1.0", optional = true }
bevy = { version = "0.5", default-features = false }
ldtk_rust = { version = "0.5", optional = true }
morton-encoding = "2.0"
log = "0.4"
serde_json = { version = "1.0", optional = true }
tiled = { version = "0.9", default-features = false, optional = true }

[dev-dependencies]
bevy = { version = "0.5", default-features = true }
rand = "0.8"
env_logger = "0.9"
